# Generated by Django 3.1.2 on 2020-10-02 10:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('progress_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='sub_text',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
