# Generated by Django 3.1.2 on 2020-10-02 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress_tracker', '0002_topic_sub_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='last_text',
            field=models.CharField(default='a', max_length=100),
        ),
    ]
