# Generated by Django 3.1.2 on 2020-10-02 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress_tracker', '0003_topic_last_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='very_last_text',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='topic',
            name='last_text',
            field=models.CharField(default='', max_length=100),
        ),
    ]
