# Generated by Django 3.1.2 on 2020-10-02 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progress_tracker', '0004_auto_20201002_1030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='last_text',
            new_name='detail_text',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='sub_text',
            new_name='time_stamp',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='very_last_text',
            new_name='unnessecary_last_text',
        ),
    ]
