# Generated by Django 3.1.2 on 2020-10-02 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progress_tracker', '0005_auto_20201002_1034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='text',
            new_name='title',
        ),
    ]
