# Generated by Django 3.1.2 on 2020-10-02 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progress_tracker', '0007_entry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='time_stamp',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='unnessecary_last_text',
        ),
    ]
