# Generated by Django 3.1.2 on 2020-10-02 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progress_tracker', '0008_auto_20201002_1106'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Entry',
            new_name='Report',
        ),
    ]
