# Generated by Django 3.1.2 on 2020-10-02 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progress_tracker', '0009_auto_20201002_1130'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'verbose_name_plural': 'Reports'},
        ),
    ]
